name: Create Release

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    tags:
      - v*  # Triggers on pushes to tags starting with "v"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run release script
        uses: actions/checkout@v3
        id: tag
        run: TAG_NAME=$(grep -o '<version>.*</version>' appinfo/info.xml | sed 's/<\/*version>//g') >> "$GITHUB_OUTPUT"
      - name: Run release script
        uses: actions/checkout@v3
        run: ./release.sh
      - name: Publish release package
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_release.outputs.TAG_NAME }}
          files: release.tar.gz