name: Create Release

on:
  push:
    tags:
      - v*  # Triggers on pushes to tags starting with "v"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run release script
        run: ./release.sh
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.releases.upload_url 1  }}  # Get upload URL from previous step
          asset_path: ./release.tar.gz
          asset_name: release.tar.gz
          asset_content_type: application/gzip  # Optional: Specify content type